### ISSUE TITLE
Traceback happens when juju-backup-all cannot find a juju credentials.

### ISSUE THREAD

**Issue by zxhdaze** [canonical/juju-backup-all#12]
When running a juju-backup-all command as a user who doesn't have a valid credentials to a juju, there is a traceback.
It should be changed, and user needs to be informed about the problem in a nice way.

dasm@env-infra1:~$ juju-backup-all 
2021-08-27 16:06:38,723 INFO jujubackupall.backup [config] juju client config backed up
Traceback (most recent call last):
  File "/snap/juju-backup-all/x1/bin/juju-backup-all", line 33, in <module>
    sys.exit(load_entry_point('juju-backup-all==0.1.dev63+gde6c21b', 'console_scripts', 'juju-backup-all')())
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/jujubackupall/cli.py", line 77, in main
    cli.run()
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/jujubackupall/cli.py", line 37, in run
    backup_processor.process_backups()
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/jujubackupall/process.py", line 82, in process_backups
    with connect_controller(controller_name) as controller:
  File "/snap/juju-backup-all/x1/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/jujubackupall/utils.py", line 44, in connect_controller
    run_async(controller.connect())
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/juju/loop.py", line 38, in run
    raise task.exception()
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/juju/controller.py", line 114, in connect
    await self._connector.connect_controller(controller_name, **kwargs)
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/juju/client/connector.py", line 86, in connect_controller
    controller_name = self.jujudata.current_controller()
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/juju/client/jujudata.py", line 137, in current_controller
    return self._load_yaml('controllers.yaml', 'current-controller')
  File "/snap/juju-backup-all/x1/lib/python3.6/site-packages/juju/client/jujudata.py", line 206, in _load_yaml
    with io.open(filepath, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dasm/.local/share/juju/controllers.yaml'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-08-27T19:42:21Z
 * owner: [smigiel-dariusz](https://launchpad.net/~smigiel-dariusz)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1941921)

**Comment by Pjack** [comment]
Let’s close this, as the project is more and less in maintenance mode. We should move to new solutions rather than relying on juju-backup-all.
