### ISSUE TITLE
Unit test failing: test_ran_with_timeout

### ISSUE THREAD

**Issue by zxhdaze** [canonical/juju-backup-all#13]
Current master (commit c8ffbeacbe3be3428e4f68f15545ea8abe689994), fails one unit test. Details below:

======================================================================
FAIL: test_ran_with_timeout (test_utils.TestRunWithTimeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/home/redacted/canonical/repos/bootstack/juju-backup-all/tests/unit/test_utils.py", line 205, in test_ran_with_timeout
    run_with_timeout(mock_coroutine, task)
AssertionError: JujuTimeoutError not raised

----------------------------------------------------------------------
Ran 54 tests in 0.130s

FAILED (failures=1)
sys:1: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited

**Comment by Pjack** [comment]
Let’s close this, as the project is more and less in maintenance mode. We should move to new solutions rather than relying on juju-backup-all.
