### ISSUE TITLE
Failed backup controller

### ISSUE THREAD

**Issue by zxhdaze** [canonical/juju-backup-all#15]
Voith MODEL(controller) jujumanage@infra-1:~/bootstack-backups$ juju-backup-all -l info -A -o /home/jujumanage/bootstack-backups
2022-01-19 07:36:36,244 INFO jujubackupall.backup [config] juju client config backed up.
2022-01-19 07:36:36,344 INFO jujubackupall.process [foundations-maas] Processing backups.
2022-01-19 07:36:36,361 INFO jujubackupall.process [foundations-maas] Models to process ['controller', 'default', 'openstack']
2022-01-19 07:36:36,533 INFO jujubackupall.process [foundations-maas controller] Backing up apps.
2022-01-19 07:36:36,677 INFO jujubackupall.process [foundations-maas default] Backing up apps.
2022-01-19 07:36:37,476 INFO jujubackupall.process [foundations-maas openstack] Backing up apps.
2022-01-19 07:36:45,183 INFO jujubackupall.process [foundations-maas openstack etcd] Backing up app.
2022-01-19 07:36:47,336 INFO jujubackupall.process [foundations-maas openstack etcd] Downloading backup.
Warning: Identity file /home/jujumanage/snap/juju-backup-all/1/.local/share/juju/ssh/juju_id_rsa not accessible: No such file or directory.
2022-01-19 07:36:48,984 INFO jujubackupall.process [foundations-maas openstack etcd] Backups downloaded to /home/jujumanage/bootstack-backups/foundations-maas/openstack/etcd/etcd-snapshot-2022-01-19-07.36.45.tar.gz
2022-01-19 07:36:56,106 INFO jujubackupall.process [foundations-maas openstack mysql] Backing up app.
2022-01-19 07:37:27,725 INFO jujubackupall.process [foundations-maas openstack mysql] Downloading backup.
Warning: Identity file /home/jujumanage/snap/juju-backup-all/1/.local/share/juju/ssh/juju_id_rsa not accessible: No such file or directory.
2022-01-19 07:37:33,163 INFO jujubackupall.process [foundations-maas openstack mysql] Backups downloaded to /home/jujumanage/bootstack-backups/foundations-maas/openstack/mysql/mysqldump-all-databases-202201190736.gz
2022-01-19 07:37:33,172 INFO jujubackupall.process [foundations-maas] Backing up controller.
2022-01-19 07:37:33,172 INFO jujubackupall.backup [foundations-maas] Attempt #1 for controller backup.
Traceback (most recent call last):
  File "/snap/juju-backup-all/1/bin/juju-backup-all", line 8, in <module>
    sys.exit(main())
  File "/snap/juju-backup-all/1/lib/python3.8/site-packages/jujubackupall/cli.py", line 105, in main
    cli.run()
  File "/snap/juju-backup-all/1/lib/python3.8/site-packages/jujubackupall/cli.py", line 42, in run
    backup_processor.process_backups()
  File "/snap/juju-backup-all/1/lib/python3.8/site-packages/jujubackupall/process.py", line 103, in process_backups
    controller_processor.backup_controller()
  File "/snap/juju-backup-all/1/lib/python3.8/site-packages/jujubackupall/process.py", line 124, in backup_controller
    resulting_backup_path = controller_backup.backup()
  File "/snap/juju-backup-all/1/lib/python3.8/site-packages/jujubackupall/backup.py", line 185, in backup
    ssh_run_on_machine(machine=controller_machine, command=chown_command)
  File "/snap/juju-backup-all/1/lib/python3.8/site-packages/jujubackupall/utils.py", line 110, in ssh_run_on_machine
    machine.ssh(command=command, user=user),
AttributeError: 'NoneType' object has no attribute 'ssh'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-01-19T07:48:40Z
 * owner: [ziyiwang](https://launchpad.net/~ziyiwang)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1958349)

**Comment by Pjack** [comment]
Let’s close this, as the project is more and less in maintenance mode. We should move to new solutions rather than relying on juju-backup-all.
