### ISSUE TITLE
File Not Found CA File/Path

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/juju-backup-all#55]
# Issue
I am testing out juju-backup-all and ran into the following issue:

```
Traceback (most recent call last):
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 559, in portforward_call
    websocket = create_websocket(configuration, url, headers)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 489, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_http.py", line 251, in _wrap_sni_socket
    context.load_verify_locations(cafile=cafile, capath=capath)
FileNotFoundError: [Errno 2] No such file or directory
```

# Steps to reproduce:

1. Run the [installation steps](https://github.com/canonical/juju-backup-all#installation)
2. `juju-backup-all`

# Context:

`juju whoami`
```
Controller:  microk8s
Model:       cos-model
User:        admin
```
`juju controllers`
``` 
Use --refresh option with this command to see the latest information.

Controller        Model      User   Access     Cloud/Region         Models  Nodes    HA  Version
foundations-maas  lma-maas   admin  superuser  localhost/localhost       2      1  none  3.5.3  
lxd               juju-lint  admin  superuser  localhost/localhost       2      1  none  3.5.3  
microk8s*         cos-model  admin  superuser  microk8s/localhost        4      1     -  3.5.3
```

# Thoughts
The README could have some minimal docs describing steps to configure the necessary CA files

**Comment by samuelallan72** [comment]
I could reproduce the error - here's the full output:

```
$ juju-backup-all
Traceback (most recent call last):
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 559, in portforward_call
    websocket = create_websocket(configuration, url, headers)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 489, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/websocket/_http.py", line 251, in _wrap_sni_socket
    context.load_verify_locations(cafile=cafile, capath=capath)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/juju-backup-all/21/bin/juju-backup-all", line 8, in <module>
    sys.exit(main())
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/jujubackupall/cli.py", line 106, in main
    cli.run()
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/jujubackupall/cli.py", line 42, in run
    backup_report = backup_processor.process_backups()
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/jujubackupall/process.py", line 101, in process_backups
    controller_processor.backup_models(omit_models=omit_models)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/jujubackupall/process.py", line 139, in backup_models
    with connect_model(self.controller, model_name) as model:
  File "/snap/juju-backup-all/21/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/jujubackupall/utils.py", line 58, in connect_model
    model = run_async(controller.get_model(model_name))
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/jujubackupall/async_handlers.py", line 25, in run_async
    return loop.run_until_complete(func)
  File "/snap/juju-backup-all/21/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/juju/controller.py", line 631, in get_model
    await model._connect_direct(**kwargs)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/juju/model.py", line 733, in _connect_direct
    await self._connector.connect(**kwargs)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/juju/client/connector.py", line 100, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/juju/client/connection.py", line 344, in connect
    self.proxy.connect()
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/juju/client/proxy/kubernetes/proxy.py", line 54, in connect
    self.port_forwarder = portforward(
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 1142, in connect_get_namespaced_pod_portforward
    return self.connect_get_namespaced_pod_portforward_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 1229, in connect_get_namespaced_pod_portforward_with_http_info
    return self.api_client.call_api(
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/snap/juju-backup-all/21/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 562, in portforward_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: [Errno 2] No such file or directory


❯ juju controllers
update.go:85: cannot change mount namespace according to change mount (/run/user/1000/doc/by-app/snap.juju /run/user/1000/doc none bind,rw,x-snapd.ignore-missing 0 0): cannot inspect "/run/user/1000/doc": lstat /run/user/1000/doc: permission denied
Use --refresh option with this command to see the latest information.

Controller  Model  User   Access     Cloud/Region         Models  Nodes    HA  Version
localhost   -      admin  superuser  localhost/localhost       1      1  none  3.4.6
microk8s*   cos    admin  superuser  microk8s/localhost        2      -     -  3.4.6

```

I saw https://github.com/canonical/juju-backup-all/issues/20 which suggests that juju-backup-all simply doesn't support k8s clouds right now.

Some possible next steps:

- update the docs to explain which type of controllers are supported
- update the code to detect when juju-backup-all is being run against an unsupported controller type
- add support for k8s controllers

**Comment by jneo8** [comment]
The error happen here: https://github.com/juju/juju/blob/e6c41fc5333c166c6460041aaa4428a77ab321a3/cmd/modelcmd/modelcommand.go#L599

**Comment by Pjack** [comment]
Revision 36 is available in stable and should fix this issue
https://charmhub.io/juju-backup-all
